### ISSUE TITLE
Current version broken?

### ISSUE THREAD

**Issue by deemr-pablo** [fastlane/boarding#104]
I have set up my boarding page following the instructions here and I get:

```
We're sorry, but something went wrong.
If you are the application owner check the logs for more information.

```
When I then tried running the demo https://boarding.herokuapp.com/, i get the same error. 
Is the tool broken?

**Comment by harkmall** [comment]
+1 experiencing this too

**Comment by ohwutup** [comment]
Hey @deemr-pablo, I am also seeing that error when I go to that link. We are investigating now, but in the meantime can you please share the output that you are seeing in logs?

Are you able to run your _boarding_ page locally?

**Comment by deemr-pablo** [comment]
Hello,  thanks for the replay. 
It was actually my fault that my deploy didn't work. I had a wrong ITC_APP_ID in the config vars. Correcting that fixed the issue.
