### ISSUE TITLE
Potential security vulnerability 

### ISSUE THREAD

**Issue by farice** [fastlane/boarding#114]
Shortly (couple of hours) after launching my application I received an alert to verify my sign in on a device somewhere in China. Thankfully, I had two step verification on my account so I was able to reject the user from hacking in to my account.

I have not looked into the vulnerability thoroughly and of course it is somewhat speculative that I'm assuming it's related to Boarding. I am curious to discover whether the password is even encrypted on the server.

For the time being, I'd recommend caution while using this application--at the least one should sign up for two-step verification.

**Comment by KrauseFx** [comment]
Thanks for submitting this issue. _boarding_ is completely self-hosted and you are storing the password on your server. If you used the Heroku button, you provided the login credentials via environment variables, which are then stored on Heroku. If you share some more information about your setup, it's easier to help 👍

**Comment by farice** [comment]
@KrauseFx Thanks for the message back. That's what I meant when I said encrypted on the server--I know that it is the self-launched Heroku server. However, I was curious whether environment variables could be accessed by a malicious user. 

After looking into it, it's clear that that is not the case. So, it's likely the hack was a genuine coincidence. Thanks again.
