### ISSUE TITLE
Invalid username and password combination

### ISSUE THREAD

**Issue by docterd** [fastlane/boarding#12]
Since some days I get following error message
```
Invalid username and password combination. Used 'xxx@xxx.com' as the username.
```
```
    def login
      return if @spaceship
      @spaceship = Spaceship::Tunes.login(user, password)
    end

    def set_app_details
```
Changing password or removing and readding the user didn't work as a workaround.

**Comment by docterd** [comment]
Deleting /tmp/spaceship_itc_login_url.txt fixed the issue.

**Comment by KrauseFx** [comment]
Which version of `spaceship` are you using?

**Comment by docterd** [comment]
I was also trying spaceship 0.5.3 after I saw a commit message related to this problem. I think I just borked some local permissions.
