### ISSUE TITLE
Is it possible to implement boarding in our website that is build on Squarespace?

### ISSUE THREAD

**Issue by klemenzagar91** [fastlane/boarding#122]
Im iOS developer and not really used to programming for web. But I learned how to create boarding page via heroku. 

But for our current project we have a landing page built on squarespace. There is a signup form for our beta. and Im wondering if there is a way to implement boarding feature that will send email addresses to our itunes connect.

**Comment by KrauseFx** [comment]
Sorry that's not possible, however you could easily host your own Heroku container and then show that inside an `iframe` 👍

**Comment by joshdholtz** [comment]
Closing this since no recent responses and a solution was presented 🙃
