### ISSUE TITLE
Something went wrong try again

### ISSUE THREAD

**Issue by soheil** [fastlane/boarding#13]
This error happens every now and then for some users. I have been able to reproduce it but it doesn't alway fail sometimes it works: fname: s lname: y email: sy@yahoo.com

ne ideas?

**Comment by KrauseFx** [comment]
You'll have to look at the server logs on Heroku. You'll see the error message there. It can have many reasons, usually it's invalid credentials or an invalid app identifier.

**Comment by soheil** [comment]
Ok I will but those two cannot be the problem because like I said it worked
before and works for some users but not always...

**Comment by soheil** [comment]
Not sure why this is happening: (it works if you refresh the post request)
```
 Completed 200 OK in 76ms (Views: 75.3ms)

2015-09-04T18:28:51.321934+00:00 app[web.1]: I, [2015-09-04T18:28:50.891812
#3]  INFO -- :   Parameters: {"utf8"=>"✓",
"authenticity_token"=>"3qZokcIcPjOLtY/Xux+tJH8zyWrYIv/IFv0fZoGrF8n+2eX+DslNgbPUti5AFfE08Bh/WzpRKUADaUNmlOuDlQ==",
"first_name"=>"s", "last_name"=>"y", "email"=>"sy@yahoo.com",
"commit"=>"Get Beta Access"}

2015-09-04T18:28:51.321941+00:00 app[web.1]:
/app/vendor/bundle/ruby/2.0.0/gems/spaceship-0.5.1/lib/spaceship/tunes/tunes_client.rb:334:in
`testers'

2015-09-04T18:28:51.321937+00:00 app[web.1]: F, [2015-09-04T18:28:51.321638
#3] FATAL -- : #<Spaceship::Client::UnexpectedResponse: {"data"=>nil,
"messages"=>{"warn"=>nil, "error"=>["Unauthorized access"], "info"=>nil},
"statusCode"=>"ERROR"}>

```

**Comment by KrauseFx** [comment]
Could you verify your Heroku instance is using the latest version of `spaceship`?

**Comment by soheil** [comment]
I deployed 6 days ago, is there a simple way to update my heroku instance?

**Comment by tompowered** [comment]
I just deployed today and ran into similar problems. Here's the error in the logs:

>
2015-09-08T22:38:28.737321+00:00 app[web.1]: F, [2015-09-08T22:38:28.736847 #3] FATAL -- : #<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Unauthorized access"]}, "statusCode"=>"ERROR"}>

**Comment by KrauseFx** [comment]
@tompowered Could you make sure to run the latest version of `spaceship`? Also, try restarting the machine.

**Comment by soheil** [comment]
I've done both to no avail.

**Comment by tompowered** [comment]
@KrauseFx I used the Deploy to Heroku button on the GitHub page - does that not use the latest version of `spaceship`?

**Comment by KrauseFx** [comment]
Ah, that's because I commited the `Gemfile.lock` @tompowered, I'll push a new version :+1:

**Comment by KrauseFx** [comment]
@tompowered Could you try using the `Heroku` button again? :rocket:

**Comment by tompowered** [comment]
@KrauseFx Success! No issues.

**Comment by KrauseFx** [comment]
Yeah :rocket:

**Comment by Benmidi** [comment]
I'm experiencing this issue. I created my initial heroku build 24 days ago. I tried pulling the latest and pushing; still had the issue. I then went back to the Heroku button and made a new one; still seeing the error. Of note, the emails are being added to TestFlight just fine. I noticed that iTunes Connect got a fresh coat of paint today... maybe they modified their response.

**Comment by dimmdesign** [comment]
@KrauseFx I've deployed using the deploy button and the issue still remains. Used push/pull the latest version of Boarding using Heroku toolbelt... Still getting `#<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["Forbidden"]}, "statusCode"=>"ERROR"}>`

Any ideas?

**Comment by JohnClema** [comment]
As of today I am getting the exact same issue (without the forbidden error bit)

`#<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>[""]}, "statusCode"=>"ERROR"}>`
