### ISSUE TITLE
Rails development mode configuration

### ISSUE THREAD

**Issue by StRibbon** [fastlane/boarding#14]
Hello,

I am trying to style the page in rails development mode but I cannot run the server locally due to many errors. I figure it has to do with storing ITC variables but I'm not sure where to put them and how. I imagine in Rails 4, it would be in the 'secrets.yml' under development or production... Can someone please give me more explicit instructions. I am new to Fastlane/boarding and but I have all the variables from the Heroku config. Thank you!

**Comment by KrauseFx** [comment]
You can just set the environments variables

```sh
export DELIVER_USER="user@email.com"
...
rails s
```

**Comment by StRibbon** [comment]
Thank you! figured it out :)
