### ISSUE TITLE
Question: best way to setup testing / alerts for when boarding -> ITC is not working?

### ISSUE THREAD

**Issue by cms5x** [fastlane/boarding#162]
Recently, a potential user tried to sign up via our boarding site and got an error, because we had not updated our boarding app after the latest ITC changes (groups of external testers I think). 

Is there a way to script "dry run" style testing (I.e. force boarding to communicate with ITC but not actually create a new tester that counts against the 2000 tester limit)? (So that I can be alerted when the test fails and figure out if it is an issue on our end, with boarding, or with ITC...)

Thanks, apologies if this has been asked and answered I did not find it in a quick search.
-Chris

**Comment by KrauseFx** [comment]
You can set the `ITC_IS_DEMO` environment variable 👍

**Comment by cms5x** [comment]
Thanks!
