### ISSUE TITLE
NoMethodError: undefined method `email' when registering user

### ISSUE THREAD

**Issue by albertodebortoli** [fastlane/boarding#166]
Encountering error when registering user

<img width="342" alt="screen shot 2017-05-31 at 20 01 59" src="https://cloud.githubusercontent.com/assets/653112/26648970/10f990ae-463c-11e7-9714-b34f241897fa.png">

```
app[web.1]: #<NoMethodError: undefined method `email' for #<Spaceship::Tunes::Member:0x007f76809e0a90>>
app[web.1]: /app/app/services/boarding_service.rb:121:in `find_app_tester'
app[web.1]: /app/app/services/boarding_service.rb:42:in `add_tester'
app[web.1]: /app/app/controllers/invite_controller.rb:91:in `create_and_add_tester'
app[web.1]: /app/app/controllers/invite_controller.rb:74:in `submit'
```

**Comment by angelcustodio** [comment]
Same error here :/

**Comment by angelcustodio** [comment]
Your ITC user should have admin privileges, if not, the app won't work properly :/
There's a conversation about this here and we all arrived to the same point https://github.com/fastlane/boarding/issues/53

**Comment by taquitos** [comment]
We recently made an update so that you need either `Admin` or `App Manager` 🎉

**Comment by albertodebortoli** [comment]
Thanks guys, I've now seen #137. My bad in misreading the permissions in iTC.
