### ISSUE TITLE
Dockerized version available

### ISSUE THREAD

**Issue by emcniece** [fastlane/boarding#167]
Hey folks, just wanted to drop a line about a Docker container for Boarding.

https://github.com/emcniece/docker-boarding

https://hub.docker.com/r/emcniece/docker-boarding/

This container clones master branch of this repo. A better paradigm would be to create a Dockerfile in fastlane/boarding and `ADD . /app` instead of `RUN git clone https://github.com/fastlane/boarding.git` - that change is easy enough. Does anyone feel like this would be a welcome PR?

Feel free to close this issue!

**Comment by KrauseFx** [comment]
That's awesome, thanks for sharing. Yeah, it would be great to add the instructions to the `boarding` README 👍

**Comment by emcniece** [comment]
Can do. 

Would you like a Dockerfile added directly to fastlane/boarding, or would you prefer to keep the projects separate?

**Comment by emcniece** [comment]
bump @KrauseFx

**Comment by KrauseFx** [comment]
Having it separate would be good, as we don't have the know how to maintain it. Feel free to submit a PR to link to that doc, happy to merge 👍
