### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by madangosain** [fastlane/boarding#17]
How to submit build to Apple App Store as pre-release from xcode project. I am trying to automate Unity3d to IOS app submission. Unity3d does export to xcode project using command line. Can deliver take input as xcode project path instead of ipa?

**Comment by KrauseFx** [comment]
You submitted this issue on the `boarding` repository. You probably meant to submit it to `fastlane`.

You should take a look at https://github.com/fastlane/examples to see how other companies use `fastlane` to automate their setup :+1:

**Comment by KrauseFx** [comment]
I'll close this issue for now
