### ISSUE TITLE
boarding.herokuapp.com is down

### ISSUE THREAD

**Issue by 2manyprojects2littletime** [fastlane/boarding#170]
<img width="999" alt="screen shot 2017-06-13 at 11 40 41 am" src="https://user-images.githubusercontent.com/6059148/27088133-42df20f2-502d-11e7-961d-7a07738cd453.png">

**Comment by KrauseFx** [comment]
Ah nice, thanks for letting us know, I'm on it 👍

**Comment by KrauseFx** [comment]
It's fixed now 🚀
