### ISSUE TITLE
`#<NoMethodError: undefined method `[]' for nil:NilClass>` -> Something went wrong, please contact the application owner

### ISSUE THREAD

**Issue by iliaskarim** [fastlane/boarding#18]
Hi Felix,

Thanks for putting all the great tools together!

We have run into an issue running and deploying `boarding`.

Even though `boarding` successfully creates a tester and adds him/her to the application in iTunes Connect, the web app __always__ responds with the message "Something went wrong, please contact the application owner" along and prints the following output to the log:
```
Successfully created tester foo@bar.com
Addding tester to application
Done
#<NoMethodError: undefined method `[]' for nil:NilClass>
/Users/ilias/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/base.rb:41:in `lookup'
/Users/ilias/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/base.rb:43:in `lookup'
/Users/ilias/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/base.rb:28:in `get'
/Users/ilias/.rbenv/versions/2.0.0-p643/lib/ruby/gems/2.0.0/gems/spaceship-0.6.1/lib/spaceship/base.rb:84:in `block (3 levels) in mapping_module'
/Users/ilias/Desktop/cf-boarding/app/controllers/invite_controller.rb:149:in `block in testing_is_live?'
/Users/ilias/Desktop/cf-boarding/app/controllers/invite_controller.rb:148:in `each'
/Users/ilias/Desktop/cf-boarding/app/controllers/invite_controller.rb:148:in `testing_is_live?'
/Users/ilias/Desktop/cf-boarding/app/controllers/invite_controller.rb:65:in `submit'
```

(I've also tried with Ruby 2.2.3 and got the same results.)

Any idea what's going on here? Its the same for new users as well as users that have already signed up. I peeked in spaceship/base.rb for a hot second but unfortunately I'm not particularly well-versed in the intricacies of Ruby.

**Comment by KrauseFx** [comment]
Hey, thanks for reporting this issue. This is probably related to the new iTunes Connect (https://github.com/KrauseFx/deliver/pull/259). I'm still working on migrating all tools to make use of the updated API.

**Comment by sebyddd** [comment]
+1. I'm facing the same situation.

**Comment by KrauseFx** [comment]
Thanks, I can reproduce this error. This was due to the change on iTunes Connect. I'll push a new version in the next few minutes.

**Comment by KrauseFx** [comment]
Could you update to the latest version and let me know if that works for you? :+1:

**Comment by neil477** [comment]
@KrauseFx Still seeing this error

**Comment by iliaskarim** [comment]
The fix worked! Thanks for your hard work

I did notice a different issue with your email validation, however. Emails with multiple consecutive periods (e.g. `first...last@gmail.com`) fail with the error: `#<Spaceship::TunesClient::ITunesConnectError: The email must be in the format: contact@example.com. The email must be in the format: contact@example.com.>` after the tester is created and added.

Want me to open a new issue on Spaceship? :)

**Comment by iliaskarim** [comment]
As an aside, do you think it would be possible to report error messages like for example email validation to the user? It would be handy in diagnosing issues like this. Right now an invalid email returns the same error message `Something went wrong, please contact the application owner`

**Comment by KrauseFx** [comment]
Good point. You could easily catch exceptions [here](https://github.com/fastlane/boarding/blob/master/app/controllers/invite_controller.rb#L49-L57).

I'm not sure how much information we should expose to the user to be honest. For example the error message might contain your username, which you might not want to share with the public.

**Comment by iliaskarim** [comment]
Cool, thanks
