### ISSUE TITLE
null null testers showing up

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/boarding#184]
Has anyone else seen this after setting up boarding?:

<img width="748" alt="screen shot 2017-11-08 at 12 00 11 am" src="https://user-images.githubusercontent.com/7799267/32535595-e04ac9dc-c417-11e7-8720-07b9137b95f3.png">

**Comment by kdawgwilk** [comment]
We are not using boarding heavily now that our app has launched in the App Store so I can't confirm if this is still an issue :(

**Comment by joshdholtz** [comment]
Not a problem! Thanks for the quick reply. Will close this for now but feel free to comment back if this happens again 💪
