### ISSUE TITLE
Boarding as Rails Engine

### ISSUE THREAD

**Issue by netbe** [fastlane/boarding#19]
Hi,

I am thinking about integrating Boarding on an existing heroku Rails app, so I guess the way to do it is via Rails Engine, I am willing to do it and contribute back but any any help or guidance on that subject would be appreciated.

Thanks

**Comment by KrauseFx** [comment]
Most code is part of [spaceship](https://github.com/fastlane/spaceship), the only thing that is part of `boarding` can be found [here](https://github.com/fastlane/boarding/blob/master/app/controllers/invite_controller.rb). 

Basically you can easily add `spaceship` as gem dependency to your Rails application and use the `spaceship` API directly.

**Comment by netbe** [comment]
Ok so if I get it right, it's not that worth it and better just add this to my app directly. Is it still interesting to do a PR to make it a Rails Engine ?

**Comment by KrauseFx** [comment]
`boarding` is more a proof on concept really on how to use `spaceship` on your server. So yes, please just use the `spaceship` in your application and use it for whatever you want to build with it :+1:

**Comment by KrauseFx** [comment]
Also, let me know what you build with it, I'm super curios

**Comment by netbe** [comment]
Nothing special, it's just that I didn't want to deploy an extra instance, so put the form on the backend server.

But about the ITC password and email, I don't really like to leave that in the heroku config in clear. Do you usually create a custom appleid to work with spaceship? If yes, which kind of permissions do you give it?

**Comment by KrauseFx** [comment]
I usually use the Mac OS X Keychain to store all passwords and only specify the username. Unfortunately there is no Keychain on Heroku, so that's not an option.

**Comment by joshdholtz** [comment]
Closing this as question/suggestions have been answered 👍 This can easily be moved over to an existing Ruby backend by using `Spaceship` directly
