### ISSUE TITLE
Layout customization failed

### ISSUE THREAD

**Issue by berasamas** [fastlane/boarding#194]
I followed the instructions below, but couldn't find how to insert environment variables ITC_USER, ITC_PASSWORD,...  I just want to modify the file en.yml.

> Install the Heroku CLI
> 
> Download and install the Heroku CLI.
> 
> If you haven't already, log in to your Heroku account and follow the prompts to create a new SSH public key.
> 
> $ heroku login
> Clone the repository
> 
> Use Git to clone edificiocuritybas's source code to your local machine.
> 
> $ heroku git:clone -a edificiocuritybas
> $ cd edificiocuritybas
> Deploy your changes
> 
> Make some changes to the code you just cloned and deploy them to Heroku using Git.
> 
> $ git add .
> $ git commit -am "make it better"
> $ git push heroku master

**Comment by joshdholtz** [comment]
@berasamas The heroic environment variables can be modified through the Heroku web dashboard (see image below) or with a Heroic CLI command `heroku config:set ITC_USER=your@email.com`

<img width="898" alt="screen shot 2018-03-29 at 4 48 14 pm" src="https://user-images.githubusercontent.com/401294/38115283-0f979030-3371-11e8-8db2-619760e20fe9.png">

Happy fastlaning 🚀
