### ISSUE TITLE
Fake signups?

### ISSUE THREAD

**Issue by robvolk** [fastlane/boarding#208]
I'm seeing a dozen or so fake signups every day from random email addresses.  I've received a few unsubscribe emails from the people, as a reply from the invite email.  It seems like someone's submitting emails to my Boarding site to see what happens, possibly to try and validate them.  Not sure exactly.

Is anyone else seeing this?  Has anyone implemented a Captcha or any other honeypots to combat this?

**Comment by KrauseFx** [comment]
Mh, I haven't seen this for any of my projects, and I think you're the first one reporting this.

**Comment by robvolk** [comment]
I secured the page by requiring a password with the `ITC_TOKEN` env var and that should fix the issue.

If we added a honeypot to the signup form, that would also fix it, and we wouldn't need to ask users for a password.  Anyway that's a new feature, so I'll close this.
