### ISSUE TITLE
Heroku having Application error

### ISSUE THREAD

**Issue by evilDave** [fastlane/boarding#216]
Noticed that my fork of boarding is not working any more. Same issue with the example in the readme. 

This is the first error in the log:

[4] ! Unable to load application: Spaceship::Tunes::Error: {"authType"=>"sa"}

**Comment by rmoriz** [comment]
same here. We've had an older version running that crashed recently on boot but also the latest master branch seems not to work.

**Comment by evilDave** [comment]
If I had to guess I’d say something changed at the iTunes end, this version was working last week. Someone noticed today that it was down.

**Comment by rmoriz** [comment]
so it seems like it is working again…

**Comment by jamesmontemagno** [comment]
Hmm I seem to get:  at=error code=H10 desc="App crashed" 

Was working yesterday.

**Comment by jamesmontemagno** [comment]
In fact it looks like the same as yours:
```
2018-05-23T21:27:18.181575+00:00 app[web.1]: bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.3.0/bin/puma)
2018-05-23T21:27:18.181578+00:00 app[web.1]: Spaceship::TunesClient::ITunesConnectError: {"authType"=>"sa"}
```

**Comment by jamesmontemagno** [comment]
I also tried a deploy to Azure and getting the same issue :(

Anyone find a work around?

**Comment by rmoriz** [comment]
see https://github.com/fastlane/fastlane/issues/12577#issuecomment-390811299

**Comment by evilDave** [comment]
That is it. Meant to jump to post the same thing.
