### ISSUE TITLE
Feature Request: Show required fields 

### ISSUE THREAD

**Issue by kostiakoval** [fastlane/boarding#22]
Add `*` sign to required field (the email)

**Comment by KrauseFx** [comment]
Feel free to submit a pull request adding the `*` :wink:

**Comment by kostiakoval** [comment]
I will try :) sorry for bothering you

**Comment by KrauseFx** [comment]
Don't worry, thanks for taking the time

**Comment by KrauseFx** [comment]
Thanks to @abookyun this is now implemented :+1:

**Comment by kostiakoval** [comment]
thanks @abookyun :) I will try to contribute next time

**Comment by abookyun** [comment]
:smile:
