### ISSUE TITLE
Heroku Deployment - Archive not found

### ISSUE THREAD

**Issue by JohannesDeml** [fastlane/boarding#231]
I'm having issues with deploying the app on heroku. The data I used was the same I had before (I deleted the old app since the old version was on there pretty long and had an error).

![image](https://user-images.githubusercontent.com/4518980/49342399-467f3a00-f65b-11e8-9ab2-e017cf0c7df3.png)

Any ideas?

**Comment by JohannesDeml** [comment]
The problem seems to be fixed, I was able to run the script again. Thanks for the update!

**Comment by KrauseFx** [comment]
Sorry for the late reply, glad it's working now
