### ISSUE TITLE
Fastlane update to 2.120

### ISSUE THREAD

**Issue by FinHorsley** [fastlane/boarding#245]
Are there any plans to update the Fastlane version to 2.120 when [#14545](https://github.com/fastlane/fastlane/pull/14545) is uploaded to [Fastlane RubyGem](https://rubygems.org/gems/fastlane)?

**Comment by janpio** [comment]
fastlane 2.120.0 is already published.

Doesn't the app also already use it? 
https://github.com/fastlane/boarding/blob/bb07a09e18576aec8387e69c045797caf088b799/Gemfile#L27

**Comment by FinHorsley** [comment]
Is it as simple as running `bundle update` then to move to 2.120?

**Comment by janpio** [comment]
It might be. Never used or developer for `boarding`, so I can't really help here. Did you try it?

**Comment by jabeler** [comment]
Unfortunately Boarding still seems to be broken, even when using Fastlane 2.120.0.

https://gist.github.com/jabeler/6d3ebfc91a1a0ce66d5f619d2041441a

**Comment by jabeler** [comment]
Interesting note, if I drop the ITC_APP_TESTER_GROUPS variable it will deply and work just fine.

**Comment by joshdholtz** [comment]
Got a PR up for fixing this ^^ 💪
