### ISSUE TITLE
Heroku error

### ISSUE THREAD

**Issue by jhendley25** [fastlane/boarding#26]
It looks like the puma config was causing issues with deploying to heroku: I was getting "uninitialized constant ActiveRecord (NameError)" when the puma process was starting up. Changing the on_worker_boot block like so fixed it for me: 

```ruby
on_worker_boot do
  ActiveSupport.on_load(:active_record) do
    config = ActiveRecord::Base.configurations[Rails.env] ||
                Rails.application.config.database_configuration[Rails.env]
    config['pool'] = ENV['MAX_THREADS'] || 5
    ActiveRecord::Base.establish_connection(config)
  end
end
```

**Comment by KrauseFx** [comment]
Okay, I'll revert https://github.com/fastlane/boarding/pull/24

**Comment by KrauseFx** [comment]
Thanks for letting me know, please try again and let me know if that works :+1:

**Comment by jhendley25** [comment]
Yep, that fixed it. :+1:
