### ISSUE TITLE
Deploying to AWS Elastic Beanstalk?

### ISSUE THREAD

**Issue by 0xced** [fastlane/boarding#27]
Has anybody tried to deploy boarding on Elastic Beanstalk? Are there some special steps to take?

**Comment by KrauseFx** [comment]
It is a standard Rails project, so it should be straight forward. Most people just use Heroku, as it's easy and free for a project like `boarding`. Let me know how it works with Beanstalk if you try it out.

**Comment by 0xced** [comment]
It worked fine. I only had two issues.

1. The latest ruby version available on AWS is 2.2.2 so I had to update the Gemfile.
2. In addition to `ITC_*` environment variables, I had to set the `SECRET_KEY_BASE` environment variable which is apparently a standard Rails thing.

**Comment by KrauseFx** [comment]
@0xced sounds good :+1:

**Comment by RishabhTayal** [comment]
@0xced I was also able to successfully deploy the app on AWS and set the env vars. However I am getting 404 not found error. Any idea why?

![screenshot 2018-08-27 11 26 33](https://user-images.githubusercontent.com/2100166/44671791-19801300-a9ec-11e8-8d6a-b5bcdda6d0d3.png)

**Comment by 0xced** [comment]
I have no idea sorry, the last time I used AWS was 3 years ago when I installed boarding and I don't remember any details.

**Comment by RishabhTayal** [comment]
no worries. will keep digging. 👍

**Comment by RishabhTayal** [comment]
Looks like the issue is similar to this: 
https://github.com/fastlane/fastlane/issues/5662#issuecomment-256235706
