### ISSUE TITLE
Restrict access to certain email domains

### ISSUE THREAD

**Issue by ruddfawcett** [fastlane/boarding#42]
I was wondering if anyone had interest in an feature that restricted signups to a certain domain name?  AKA only allow external users from your school or organization to sign up.  I'm thinking `RESTRICTED_DOMAIN=school.edu`?  If the value is null/the variable is nonexistent it would default to normal behavior.

I have implemented this feature and am just trying to get a sense of if anyone else would benefit from it.

In the meantime, you can drop something like this into your `app/controllers/invite_controller.rb`, at around line 22. 

```ruby
if email.split("@").last != "school.edu"
  @message = "Sorry! Early access is currently restricted to people within the @school.edu domain.  We will be opening it up soon, though!"
  @type = "warning"
  render :index
  return
end
```

**Comment by KrauseFx** [comment]
@ruddfawcett I like the idea and would happily merge a pull request :+1: You can use an environment variable to pass the email host.

**Comment by ruddfawcett** [comment]
@KrauseFx yep -- current implementation... I'll send a PR when I get a chance.

```ruby
if ENV["RESTRICTED_DOMAIN"]
  if email.split("@").last != ENV["RESTRICTED_DOMAIN"]
    @message = "Sorry! Early access is currently restricted to people within the #{ENV["RESTRICTED_DOMAIN"]} domain.  We will be opening it up soon, though!"
    @type = "warning"
    render :index
    return
  end
end
```

**Comment by KrauseFx** [comment]
Interesting, looks great. Thank you @ruddfawcett :+1:
