### ISSUE TITLE
Unable to complete deployment on Heroku

### ISSUE THREAD

**Issue by akramhussein** [fastlane/boarding#44]
Believe the new iTunes Connect changes have rendered the deployment process for Boarding broken. 
Deployed last night before the changes and worked. Site no longer worked - I assumed this was because Spaceship etc needed updating. Deleted the Heroku app to try again. Deployed at 11:15AM with fresh Heroku App, but received following error message.

![screen shot 2015-11-12 at 11 10 25](https://cloud.githubusercontent.com/assets/586938/11116992/26ef4632-892e-11e5-9a7e-1079e7b0956f.png)

**Comment by akramhussein** [comment]
Weirdly, clicking "Deploy for Free" a few times has made this work.

**Comment by akramhussein** [comment]
Dependency commit - 28486d2  - seems to have fixed this.

**Comment by KrauseFx** [comment]
:+1:
