### ISSUE TITLE
Wrong instructions for updating Heroku

### ISSUE THREAD

**Issue by jvanzummeren** [fastlane/boarding#46]
Just wanted to point out that the 'Recommended' instruction do not work as expected.

This does not work:
```heroku clone --app [app-name]```

Should be:
```
heroku git:clone -a [app-name]
```
<https://devcenter.heroku.com/articles/git-clone-heroku-app>

But other than that, it works great, thanks!

**Comment by KrauseFx** [comment]
Thanks, this is now updated :+1:
