### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by krishan711** [fastlane/boarding#48]
My boarding landing page isn't showing up (500 error), and when I check the logs it shows a bunch of html with the message "Your sign in cannot be completed because you have no trusted devices listed for your account. Visit the Apple ID site and use your Recovery Key to add trusted devices.". What's happening here? Everything was working as required a couple of weeks ago. I deployed a brand new heroic project using the deploy button and get the same error.

**Comment by jhendley25** [comment]
I'm seeing the same issue

**Comment by adamstener** [comment]
I'm getting a runtime error -  RuntimeError (Could not fetch the login URL from iTunes Connect, the server might be down): All my boarding sites are currently not working, created a new one from scratch and seeing the same issue

**Comment by iamchenchen** [comment]
same issue here.

**Comment by KrauseFx** [comment]
Please make sure to update to the latest version of `spaceship` using `bundle update`, so that your `Gemfile.lock` has the new version of `spaceship`. For more information check out the `update` section on the project page

**Comment by adamstener** [comment]
boarding.herokuapp.com has a similar issue it appears.

**Comment by KrauseFx** [comment]
Oh, thanks! It seems like `boarding` doesn't work when you're in multiple teams yet, working on it now :+1:

**Comment by KrauseFx** [comment]
It's working now: https://boarding.herokuapp.com/
Please update and make sure to set the `FASTLANE_ITC_TEAM_NAME` or `FASTLANE_ITC_TEAM_ID` value :+1:

**Comment by adamstener** [comment]
Can you update the process for making a boarding app from the github page?  I'm now not able to deploy a new app, it's not valid.

**Comment by KrauseFx** [comment]
What do you mean it's not valid? Try [this](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2Ffastlane%2Fboarding&template=https%3A%2F%2Fgithub.com%2Ffastlane%2Fboarding)

**Comment by jhendley25** [comment]
@KrauseFx I think he is referring to this error: 

Counting objects: 496, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (189/189), done.
Writing objects: 100% (496/496), 1.40 MiB | 1.61 MiB/s, done.
Total 496 (delta 321), reused 471 (delta 299)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Using set buildpack heroku/ruby
remote: -----> Ruby app detected
remote: -----> Compiling Ruby/Rails
remote: -----> Using Ruby version: ruby-2.2.3
remote: -----> Installing dependencies using bundler 1.9.7
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
remote:        You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:        You have added to the Gemfile:
remote:        * spaceship (>= 0.15.1)
remote:        You have deleted from the Gemfile:
remote:        * spaceship (>= 0.14.0)
remote:        Bundler Output: You are trying to install in deployment mode after changing
remote:        your Gemfile. Run `bundle install` elsewhere and add the
remote:        updated Gemfile.lock to version control.
remote:
remote:        You have added to the Gemfile:
remote:        * spaceship (>= 0.15.1)
remote:
remote:        You have deleted from the Gemfile:
remote:        * spaceship (>= 0.14.0)
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app
remote:
remote: Verifying deploy...
remote:
remote: !	Push rejected to arkiver-invite.
remote:
To https://git.heroku.com/arkiver-invite.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/arkiver-invite.git'


I manually cloned, bundled, and deployed and everything worked fine. Probably need to update the Gemfile.lock for the autodeploy.

**Comment by adamstener** [comment]
That is correct.
