### ISSUE TITLE
Does not support new iTunesConnect features

### ISSUE THREAD

**Issue by kdawgwilk** [fastlane/boarding#50]
This no longer works if your email is tied to multiple iTunesConnect teams :(
http://9to5mac.com/2015/06/12/wwdc-itunes-connect-testflight-limits-account-switching/
"Another nice change for developers is the ability to manage several accounts in iTunes Connect under a single username."

**Comment by KrauseFx** [comment]
That's correct, please follow this issue to be up to date https://github.com/fastlane/spaceship/issues/181

**Comment by KrauseFx** [comment]
This is now implemented, please update to the latest version :rocket:
