### ISSUE TITLE
Boarding Example Not Working

### ISSUE THREAD

**Issue by simonrice** [fastlane/boarding#54]
I'm afraid I can't be much more helpful right now, but it seems there's a crash with the example hosted at https://boarding.herokuapp.com

I'll see if I can dig out any further information for you shortly just in case it's not a trivial thing to fix - I haven't yet created an example for myself.

**Comment by KrauseFx** [comment]
Thanks, working on a fix right now

**Comment by KrauseFx** [comment]
Fixed https://boarding.herokuapp.com/ :rocket:

**Comment by simonrice** [comment]
Thank you 😃 & well done getting it fixed so quickly 🚀
