### ISSUE TITLE
It would be helpful if Boarding could use a user in the App Manager role

### ISSUE THREAD

**Issue by pzearfoss** [fastlane/boarding#63]
Right now you must use an admin user when communicating with the iTunesConnect portal.  The App Manager role can add users to testflight, but doesn't have the ability to delete apps for instance..  For security reasons, it's better to use a role with the minimum required permissions.

**Comment by dreyhomedev** [comment]
Same for the Technical role #64

**Comment by zirinisp** [comment]
I am having the same issue can only use it with admin user. Would like to see the App Manager role being able to use boarding.

**Comment by claesjacobsson** [comment]
+1

**Comment by boxenjim** [comment]
+1

**Comment by vpolouchkine** [comment]
Closing in favor of https://github.com/fastlane/boarding/issues/63
