### ISSUE TITLE
Feature-request: Specify Groups for new testers

### ISSUE THREAD

**Issue by skywinder** [fastlane/boarding#7]
It would be cool to assign separate group for users that added by `boarding`.
![screen shot 2015-07-24 at 09 39 39](https://cloud.githubusercontent.com/assets/3356474/8869051/336278dc-31e8-11e5-9344-da9042eb18f9.png)

**Comment by KrauseFx** [comment]
Sounds like a good feature. This will also require an update of `spaceship`.

**Comment by pke** [comment]
Will this ever come? @KrauseFx 
Otherwise where are the users added at the moment? As itunes connect users?

**Comment by KrauseFx** [comment]
I'd be more than happy to merge a PR adding this feature, it seems like it would be useful for sure 👍

**Comment by joshdholtz** [comment]
Closing this as this seems to be a feature now with the `ITC_APP_TESTER_GROUPS` environment variable 😊
