### ISSUE TITLE
cloning the repo always returns an empty directory

### ISSUE THREAD

**Issue by schultzjim** [fastlane/boarding#77]
I've been following the instructions exactly as shown here: https://github.com/fastlane/boarding#customize 

I'm trying to do some simple customization however I'm not getting past cloning the repo because it is an empty directory. I'm sure i'm missing something simple though.

**Comment by vpolouchkine** [comment]
Can you post what you've done so far?

**Comment by boxenjim** [comment]
sure no problem. 

1) followed these steps exactly: https://github.com/fastlane/boarding#getting-started everything worked as expected, app deployed and running
2) followed these steps exactly: https://github.com/fastlane/boarding#customize, on the cloning step it is always an empty directory

**Comment by vpolouchkine** [comment]
Looks like this is by design: http://stackoverflow.com/a/31609976/4802413

**Comment by Geeroz** [comment]
@boxenjim Have you ever get it to work? I'm having the same problem.

**Comment by wkwyatt** [comment]
@vpolouchkine Has this issue been resolved at all?  I have been getting the same thing.

**Comment by dccarmo** [comment]
Did anyone find a workaround to this?

**Comment by jessicathrasher** [comment]
My workaround was to follow the instructions for updating to a new version of boarding which will pull the code:

`heroku git:clone --app [heroku_app_name]`
`cd [heroku_app_name]`
`git pull https://github.com/fastlane/boarding`
`git push`

Now that you can see the code there you can make changes and push it back up to Heroku.
