### ISSUE TITLE
boarding creates external testers, what about internal?

### ISSUE THREAD

**Issue by jonsajdak** [fastlane/boarding#8]
I tried this workflow out and see that it creates external testers successfully. 

Would it be feasible to have it create internal testers?  I'm not sure ITC connects allows adding internal/external in the same way, or if there is some other limitation around this.

**Comment by KrauseFx** [comment]
Sorry, that's not planned right now, as it's quite risky: internal testers have access to your iTunes Connect data as they have to be in your iTunes Connect team. It wouldn't be a good idea to allow public registration for that kind of things :wink:
