### ISSUE TITLE
ITC Api Change

### ISSUE THREAD

**Issue by davoda** [fastlane/boarding#84]
"Something went wrong, please contact the application owner" is back.

Constantly returning the following error now:
`#<Spaceship::Client::UnexpectedResponse: {
"data"=>nil, 
"messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}>`

**Comment by KrauseFx** [comment]
Unfortunately that's an error on Apple's side, duplicate of https://github.com/fastlane/fastlane/issues/5200

Please also contact Apple by sending a support request or calling them. 

This is not a fastlane error, the same thing happens when you try to add an external tester using iTunes Connect

**Comment by davoda** [comment]
@KrauseFx I was able to add users on their site before. But yes, Pilot is also down :(

**Comment by KrauseFx** [comment]
@davoda What happens if you follow these steps? https://github.com/fastlane/fastlane/issues/5200#issuecomment-228186725

**Comment by pbeast** [comment]
Hi, 
I have the same probelm `(#<Spaceship::Client::UnexpectedResponse: {"data"=>nil, "messages"=>{"warn"=>nil, "info"=>nil, "error"=>["service_http_bad_response"]}, "statusCode"=>"ERROR"}>)`, but **can** create user manually using iTunesConnect. 

Can I help somehow?

**Comment by KrauseFx** [comment]
@pbeast Creating external testers? Or internal ones?

**Comment by pbeast** [comment]
@KrauseFx, externals

**Comment by KrauseFx** [comment]
@pbeast I just tried, it's not working for me

**Comment by pbeast** [comment]
@KrauseFx , hmmm. Very strange. Will check again

**Comment by samwize** [comment]
Seems like Apple fixed on their side. Adding External testers on ITC works now.

Boarding works without error too.

**Comment by KrauseFx** [comment]
I just tried both boarding and pilot, and both work without problems. I'll close this issue for now, however feel free to re-open if you're still running into issues 👍

**Comment by pbeast** [comment]
Thanks a lot
